[platformio]
src_dir = .
default_envs = cyd

[env:xiao_esp32s3]
platform = espressif32@^6.3.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

build_src_filter = +<main.cpp>

board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

[env:cyd]
platform = espressif32@^6.3.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    mikalhart/TinyGPSPlus@^1.1.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCYD_BUILD=1
    -DUSER_SETUP_LOADED=1
    -DILI9341_2_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_RGB_ORDER=0
    -DTFT_INVERSION_ON=1
    -DUSE_HSPI_PORT=1
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSMOOTH_FONT=1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=16000000

build_src_filter = +<main.cpp>

board_build.partitions = partitions_cyd.csv
board_build.filesystem = spiffs
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
